Repository hanaro5-team-last-pang/hana-hakhoe-client, pull requests merged in 2025-02, with the labels that each got.

#69 🛂 auth data 전역 상태 관리되도록 변경
  package-lock.json
  package.json
  src/app/(main)/mypage/card-settings/page.tsx
  src/app/api/user-info/route.ts
  src/app/layout.tsx
  src/components/molecules/ProfileDropdown.tsx
  src/components/organisms/Header.tsx
  src/components/organisms/MentoringListTable.tsx
  src/constant.ts
  src/context/AuthContext.tsx
  src/provider/AuthRefreshProvider.tsx
  src/provider/AuthStoreProvider.tsx
  src/stores/AuthStore.ts
  src/types/hanaHakdang.d.ts
Labels: :package: API, :recycle: refactor

#72 ♻️ 내정보 수정 페이지 API 연동 및 로그아웃 추가
  next.config.ts
  src/app/(auth)/action.ts
  src/app/(auth)/login/page.tsx
  src/app/(main)/mypage/account-settings/page.tsx
  src/app/(main)/mypage/actions.ts
  src/app/(main)/mypage/card-settings/page.tsx
  src/app/action.ts
  src/app/api/logout/route.ts
  src/components/molecules/ProfileDropdown.tsx
  src/components/organisms/Header.tsx
  src/constant.ts
  src/provider/AuthRefreshProvider.tsx
  src/stores/AuthStore.ts
  src/types/hanaHakdang.d.ts
Labels: :bug: fix bug, :package: API, :recycle: refactor

#78 🐛 role:대문자로 수정
  src/app/(main)/mypage/mentorings/page.tsx
  src/components/molecules/HeaderTab.tsx
  src/components/molecules/ProfileDropdown.tsx
  src/components/organisms/MentoringListTable.tsx
  src/components/organisms/MyPageNavbar.tsx
  src/stores/AuthStore.ts
  src/types/hanaHakdang.d.ts
Labels: :bug: fix bug

#81 👔 홈페이지 API 연결 및 코드 리펙토링
  next.config.ts
  package-lock.json
  package.json
  src/app/(main)/mypage/account-settings/page.tsx
  src/app/(main)/news/page.tsx
  src/app/page.tsx
  src/components/molecules/HeaderTab.tsx
  src/constant.ts
  src/stores/AuthStore.ts
Labels: :package: API, :recycle: refactor

#82 🐛 멘토링 개설 api 수정
  src/app/(main)/mentorings/actions.ts
  src/app/(main)/mypage/actions.ts
  src/components/template/OpenMentoringForm.tsx
Labels: :bug: fix bug

#84 ♻️ 자잘한 버그 수정 및 코드 리펙토링
  src/app/(main)/mentorings/[id]/actions.ts
  src/app/(main)/mentorings/page.tsx
  src/app/(main)/mypage/mentorings/page.tsx
  src/app/classrooms/error.tsx
  src/app/page.tsx
  src/components/organisms/MentoringIntro.tsx
  src/constant.ts
  src/utils/getRandomIndex.ts
Labels: :bug: fix bug, :package: API, :recycle: refactor

#88 :sparkles: 강의 종료 API 구현
  src/app/classrooms/_component/VideoComponent.tsx
  src/app/classrooms/action.ts
  src/hooks/useWebRTC.tsx
Labels: 🌱 feature

#89 🐛 멘토링 상세 정보 리뷰, faq 에러 처리
  src/app/(main)/mentorings/actions.ts
  src/app/(main)/mypage/type.d.ts
  src/components/organisms/Pagination.tsx
  src/components/template/MentoringFAQForm.tsx
  src/components/template/MentoringIntroduceForm.tsx
  src/components/template/MentoringReviewForm.tsx
Labels: :bug: fix bug

#90 멘티 강의실 UI 수정 및 채팅 기능 수정
  src/app/classrooms/[id]/page.tsx
  src/app/classrooms/_component/ChatComponent.tsx
  src/app/classrooms/_component/VideoComponent.tsx
Labels: :bug: fix bug

#92 :sparkles: 리뷰 남기기 API 연동
  src/app/(main)/mentorings/actions.ts
  src/app/classrooms/[id]/@modal/(.)review/page.tsx
  src/app/classrooms/[id]/page.tsx
  src/app/classrooms/[id]/review/page.tsx
  src/app/classrooms/_component/VideoComponent.tsx
  src/components/template/MentoringReviewModalForm.tsx
  src/components/template/PageModal.tsx
  src/hooks/useWebRTC.tsx
Labels: :bug: fix bug, 🌱 feature

#93 :green_heart: 빌드 이슈 수정
  README.md
  src/app/(auth)/approval/page.tsx
  src/app/(main)/news/page.tsx
  src/app/globals.css
  src/components/organisms/FAQList.tsx
  src/components/organisms/Pagination.tsx
  src/constant.ts
  tsconfig.json
Labels: :bug: fix bug
